//Automatically generated by makefile, do not edit
.n64 // Let armips know we're coding for the N64 architecture
.open "rom/Doraemon2.z64", "rom/Doraemon2.mod.z64", 0 // Open the ROM file
.include "asm/symbols.asm" // Include ct2.asm to tell armips' linker where to find the game's function(s)
.include "asm/bootPatch2.asm"
.headersize 0x7F800000
.org 0x80400000
.importobj "obj/main.o"
.close //close file
